sudo: false
dist: trusty
language: cpp
group: stable

cache:
  apt: true
  ccache: true
  directories:
    - $TRAVIS_BUILD_DIR/libraries
    - $TRAVIS_BUILD_DIR/.stack/
    - .stack-work/

matrix:
  fast_finish: true
  include:
  - compiler: gcc-6
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
          - libc++-dev
          - libc++abi-dev
          - clang-3.8
          - clang-format-3.8
          - clang-tidy-3.8
          - libnlopt-dev
    env:
      - C_COMPILER=gcc-6 CXX_COMPILER=g++-6 COVERAGE=''
  - compiler: clang-3.8
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - python3.4-venv
          - libc++-dev
          - libc++abi-dev
          - clang-3.8
          - clang-format-3.8
          - clang-tidy-3.8
          - libnlopt-dev
    env:
      - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 COVERAGE=''
  - compiler: sphinx
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - python3.4-venv
    env:
      - ALBATROSS_DOCS=true


script:
  if [[ -z $ALBATROSS_DOCS ]]; then bash ./ci/run_tests.sh || exit 1; else ./doc/build_docs.sh || exit 1; fi;


